### ISSUE TITLE
Need to reduce width of keyword search field 

### ISSUE THREAD

**Issue by neoinsight** [canada-ca/regs-consult-wet#1]
@dk-tbs Research participants in all of the Finder studies are often getting zero results (particularly in this sets that are small - like consultations) because they enter too many words in the search - as if it's Google. I'm experimenting with labelling this as 'One keyword' but we also want to make the field shorter - more like 14 characters instead of over 20. 

We tried to make it that width (@steve-h did), but the Find button became detached and stayed over on the right. Do you have any CSS wizardry you could suggest to help us - could try it out on this page - have added you as a collaborator 
https://canada-ca.github.io/regs-consult-wet/consultation/consultations-finder-en.html

**Comment by MaryBethBaker** [comment]
Hey @thomasgohard, Any suggestions for a CSS fix or someone that can help?

Thanks! mb

**Comment by DK-TBS** [comment]
Fixed!  Now you'll find a STYLE block in the HTML code, right near the form field.  There's a 50% width on the field that you can tinker with freely, and the "find" button will play along with you  :)

**Comment by neoinsight** [comment]
Thanks so much @DK-TBS
